# golang v1.20 on debian bullseye
image: golang:1.20-bullseye

stages:
  - build
  - test
  - security

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  before_script:
    - apt install -y portaudio19-dev
  script:
    - go build

test:
  stage: test
  script:
    - go test ./...
    - test $?

formatting:
  stage: test
  script:
    - test -z $(gofmt -l .)

security:
  stage: test
  before_script:
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
  script:
    - gosec ./...
    - test $?

