# golang v1.20 on debian bullseye
image: golang:1.20-bullseye

stages:
  - build
  - test
  - security

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test ./...
    - test -z $?

formatting:
  stage: test
  script:
    - test -z $(gofmt -l .)

security:
  stage: test
  before_script:
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
  script:
    - gosec ./...
    - test -z $?

